
jhipster:
  cors:
    allowed-origins: "http://backoffice.breathebinary.com"
    allowed-methods: "*"
    allowed-headers: "*"
    exposed-headers: "Authorization,Link,X-Total-Count"
    allow-credentials: true
    max-age: 1800
